secrets:
  config:
    file: server/config.json
services:
  main:
    build:
      args:
        BUILDKIT_INLINE_CACHE: '1'
        BUILDKIT_PROGRESS: 'plain'
        COMPOSE_DOCKER_CLI_BUILD: '1'
        DOCKER_BUILDKIT: '1'
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
    environment:
      - CONFIG_FILE=/run/secrets/config
    ports:
      - '4000:4000'
      - '8080:8080'
    secrets:
      - config
    volumes:
      - .:/usr/src/app
