version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '4000:4000'
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '8080:8080'
